import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { usersApi } from '../api/usersApi';
import { friendsApi } from '../api/friendsApi';
import { User, RelationshipStatus } from '../types';
import Avatar from '../components/Avatar';
import LoadingSpinner from '../components/LoadingSpinner';
import { toast } from 'react-hot-toast';

const ExplorePage: React.FC = () => {
  const navigate = useNavigate(); const [query, setQuery] = useState(''); const [users, setUsers] = useState<(User & { relationshipStatus?: RelationshipStatus })[]>([]); const [isLoading, setIsLoading] = useState(false); const [busy, setBusy] = useState<Set<string>>(new Set());
  useEffect(() => { const fetchUsers = async () => { setIsLoading(true); try { const res = query.trim() ? await usersApi.searchUsers(query) : await usersApi.getDiscoverUsers(20); setUsers(res as any); } catch (err: any) { toast.error(err?.response?.data?.message || 'Failed to load people'); } finally { setIsLoading(false); } }; const debounce = setTimeout(fetchUsers, 350); return () => clearTimeout(debounce); }, [query]);
  const sendRequest = async (target: any) => { const uid = target.id || target._id; if (!uid) return; setBusy(prev => new Set(prev).add(uid)); try { await friendsApi.sendRequest(uid); setUsers(prev => prev.map(u => u.id === uid ? { ...u, relationshipStatus: 'pending_sent' } : u)); toast.success(`Friend request sent to @${target.username}`); } catch (err: any) { toast.error(err?.response?.data?.message || 'Could not send friend request'); } finally { setBusy(prev => { const next = new Set(prev); next.delete(uid); return next; }); } };
  const actionLabel = (status?: RelationshipStatus) => status === 'accepted' ? 'Friends' : status === 'pending_sent' ? '✓ Request Sent' : status === 'pending_received' ? 'Review Request' : status === 'blocked' ? 'Blocked' : 'Add Friend';
  return <div className="page-container" style={{ maxWidth: '900px', margin: '0 auto', paddingTop: '2rem' }}><div style={{ marginBottom: '2rem' }}><h1 style={{ fontFamily: 'var(--font-heading)', fontSize: '2rem', marginBottom: '.4rem' }}>Explore People</h1><p style={{ color: 'var(--text-muted)', marginBottom: '1rem' }}>Find people, build your community and connect.</p><input type="text" className="form-input" placeholder="Search by name or username..." value={query} onChange={(e) => setQuery(e.target.value)} /></div>{isLoading ? <LoadingSpinner /> : users.length > 0 ? <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '1.25rem' }}>{users.map((person: any) => { const uid = person.id || person._id, status = person.relationshipStatus as RelationshipStatus | undefined, isBusy = busy.has(uid); const disabled = isBusy || ['accepted', 'pending_sent', 'blocked'].includes(status || ''); return <div key={uid} className="card" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', gap: '1rem' }}><Link to={`/users/${person.username}`}><Avatar src={person.profilePicture} name={person.displayName} size="lg" /></Link><div><Link to={`/users/${person.username}`} style={{ color: 'var(--text-primary)', textDecoration: 'none' }}><h3 style={{ fontSize: '1.1rem', fontWeight: 600, margin: 0 }}>{person.displayName}</h3></Link><p style={{ color: 'var(--text-muted)', fontSize: '.9rem', margin: 0 }}>@{person.username}</p>{person.bio && <p style={{ color: 'var(--text-muted)', fontSize: '.8rem', margin: '.5rem 0 0' }}>{person.bio}</p>}</div><div style={{ display: 'flex', gap: '.5rem', width: '100%' }}><Link to={`/users/${person.username}`} className="btn btn-ghost btn-sm" style={{ flex: 1 }}>View Profile</Link><button className={`btn btn-sm${disabled ? ' btn-ghost' : ' btn-primary'}`} style={{ flex: 1 }} disabled={disabled} onClick={() => status === 'pending_received' ? navigate('/friends') : sendRequest(person)}>{isBusy ? '…' : actionLabel(status)}</button></div></div>; })}</div> : <div className="card" style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-muted)' }}>No users found.</div>}</div>;
};
export default ExplorePage;
